site_name: twr-wasm - a Library for Creating C/C++ Web Assembly Modules
site_url: https://twiddlingbits.dev/docsite/
repo_url: https://github.com/twiddlingbits/twr-wasm
edit_uri: 'tree/main/docs'
site_description: Documentation and examples to show how to use twr-wasm to execute C/C++ code in a browser, using Web Assembly and clang directly.
site_dir: azure/docsite/
theme: 
  name: readthedocs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: gettingstarted/installation.md
    - Create wasm C Hello World: gettingstarted/helloworld.md
    - Key Concepts: gettingstarted/keyconcepts.md
    - Stdio: gettingstarted/stdio.md
    - Compiler, Linker, Memory: gettingstarted/compiler-opts.md
  - WASM Examples: 
    - Overview: examples/examples-overview.md
    - hello world: examples/examples-helloworld.md
    - stdio-div: examples/examples-stdio-div.md
    - stdio-canvas: examples/examples-stdio-canvas.md
    - balls: examples/examples-balls.md
    - maze: examples/examples-maze.md
    - fft: examples/examples-fft.md
    - libc++: examples/examples-libcxx.md
    - more: examples/examples-more.md
  - twr-wasm API Reference:
    - TypeScript/JavaScript: api/api-typescript.md
    - C Localization: api/api-localization.md
    - C General: api/api-c-general.md
    - C++ with libc++: api/api-libc++.md
    - C Draw 2D: api/api-c-d2d.md
    - C Console I/O: api/api-c-con.md
    - C Standard C Library: api/api-c-stdlib.md
  - More:
    - The Wasm Problem: more/wasm-problem.md
    - Debugging WASM: more/debugging.md
    - Production: more/production.md
    - Building the Source: more/building.md

  


