site_name: tiny-wasm-runtime documentation
site_url: https://twiddlingbits.dev
repo_url: https://github.com/twiddlingbits/tiny-wasm-runtime
edit_uri: 'tree/main/docs'
site_description: A lightweight and easy to use C/C++ runtime to run your C/C++ code in a browser using Web Assembly.
site_dir: azure/docsite/
nav:
  - Home: index.md
  - Getting Started:
    - Installation: gettingstarted/installation.md
    - Your First C Wasm: gettingstarted/firstwasm.md
    - Key Concepts: gettingstarted/keyconcepts.md
    - Stdio: gettingstarted/stdio.md
    - Compiler, Linker, Memory: gettingstarted/compiler-opts.md
  - Examples: 
    - Overview: examples/examples-overview.md
    - hello world: examples/examples-helloworld.md
    - stdio-div: examples/examples-stdio-div.md
    - stdio-canvas: examples/examples-stdio-canvas.md
    - balls: examples/examples-balls.md
    - maze: examples/examples-maze.md
    - fft: examples/examples-fft.md
    - more: examples/examples-more.md
  - API Reference:
    - TypeScript/JavaScript: api/api-typescript.md
    - C localization: api/api-localization.md
    - C General: api/api-c-general.md
    - C++ libc++: api/api-libc++.md
    - C Draw 2D: api/api-c-d2d.md
    - C Console I/O: api/api-c-con.md
    - C Standard C Library: api/api-c-stdlib.md
  - More:
    - The Wasm Problem: more/wasm-problem.md
    - Debugging: more/debugging.md
    - Production: more/production.md
    - Building the Source: more/building.md

theme: 
  name: readthedocs
  


